[package]
name = "obu"
version = "0.1.0"
authors = ["LudeeD <lfssilva@ua.pt>"]
edition = "2018"


[dependencies]

rocket = "0.4.1"
reqwest = "0.9.13"

protobuf = "2.4.2"
sawtooth-sdk = "0.2"
rust-crypto = "0.2.36"
openssl = "0.10"
